export enum ActivityEntityType {
  ORGANIZATION = 'ORGANIZATION',
  MEMBER = 'MEMBER',
  PROJECT = 'PROJECT',
  TASK = 'TASK',
  INVITATION = 'INVITATION',
}

export enum ActivityActions {
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_MOVED = 'TASK_MOVED',
  TASK_DELETED = 'TASK_DELETED',
}
